# Generated by Django 4.0.2 on 2022-02-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('referrer', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Id Пользователя')),
                ('username', models.CharField(blank=True, max_length=400, null=True, verbose_name='Username Пользователя')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя Пользователя')),
                ('address', models.CharField(max_length=1000, null=True, unique=True, verbose_name='Адрес')),
                ('twitter_name', models.CharField(max_length=1000, null=True, unique=True, verbose_name='Твиттер')),
                ('balance', models.FloatField(blank=True, default=0, verbose_name='Баланс')),
                ('refferals', models.IntegerField(default=0, verbose_name='Количество рефералов')),
                ('tg', models.BooleanField(default=False, verbose_name='Задачи телеграм')),
                ('twitter_tasks', models.BooleanField(default=False, verbose_name='Twitter репост')),
            ],
            options={
                'verbose_name': 'Пользовател',
                'verbose_name_plural': 'Пользователы',
            },
        ),
    ]
