# Generated by Django 4.0.2 on 2022-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_joined_airdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
    ]
